import turtle as a
for i in range(1000):
    a.hideturtle()
    a.speed(50)
    a.forward(i)
    a.left(90)
    a.forward(i)
    a.left(90)
    a.forward(i)
    a.left(90)
    a.forward(i)
    a.left(90)
    a.left(50)
    a.forward(i+2.67)
    a.penup()
    a.right(50)
    a.pendown()
    a.forward(i)
    a.left(90)
    a.forward(i)
    a.left(90)
    a.forward(i)
    a.left(90)
    a.forward(i)
    a.left(180)
    a.forward(i)
    a.left(140)
    a.forward(i+2.67)
    a.left(40)
    a.forward(i)
    a.left(90)
    a.forward(i)
    a.left(50)
    a.forward(i+2.67)
    a.left(40)
    a.forward(i)
    a.left(140)
    a.forward(i+2.67)


