import turtle as tit
while 1:
    tit.hideturtle()
    tit.speed(100)
    tit.pencolor("violet")
    tit.circle(170)
    tit.forward(10)
    tit.left(45)
    tit.pencolor("indigo")
    tit.circle(50)
    tit.pencolor("blue")
    tit.circle(70)
    tit.pencolor("green")
    tit.circle(90)
    tit.pencolor("yellow")
    tit.circle(110)
    tit.pencolor("orange")
    tit.circle(130)
    tit.pencolor("red")
    tit.circle(150)
   
